version: "3"
services:
  database:
    image: postgres
    env_file:
      - ./config/dbConfigDockerCompose.env
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - privateNetwork
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: go run main.go --configPath ./config/dbConfigDockerCompose.env
    volumes:
      - .:/app
    depends_on:
      - database
    ports:
      - "8080:8080"
    networks:
      - publicNetwork
      - privateNetwork
networks:
  publicNetwork:
    internal: false
  privateNetwork:
    internal: true
volumes:
  postgres: